apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-cicd-app
  labels:
    app: flask-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-cicd-app
  template:
    metadata:
      labels:
        app: flask-cicd-app
    spec:
      containers:
      - name: flask-cicd-app
        image: 978007052414.dkr.ecr.us-east-1.amazonaws.com/flask-cicd-app:latest
        ports:
        - containerPort: 5000


        
