apiVersion: v1
kind: Service
metadata:
    name: flask-cicd-service 
spec:
    type: LoadBalancer
    selector:
        app: flask-cicd-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 5000